version: "3.0"

services:
  db:
    container_name: mongo
    image: mongo:7.0.11
    restart: always
    ports:
      - "7202:27017"
    volumes:
      - ./dbData:/data/db
    networks:
      - mean_network

  server:
    container_name: server
    image: node:20.14.0
    restart: always
    volumes:
      - ./server:/usr/src/app
    networks:
      - mean_network
    working_dir: /usr/src/app
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /usr/src/app
        mkdir -p /usr/src/app/data
        cd /usr/src/app
        npm install
        npm start
    ports:
      - "7201:3000"
    depends_on:
      - db

  web:
    container_name: client
    image: node:20.14.0
    restart: always
    volumes:
      - ./client:/app
    networks:
      - mean_network
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /app
        cd /app
        npm install
        npm start
    ports:
      - "7200:4200"
    depends_on:
      - server

networks:
  mean_network:
    driver: bridge
    ipam:
      config:
        - subnet: 7.2.0.0/24
          gateway: 7.2.0.1